var patternImg = new Array;
/*------------------------------------------------------*/
patternImg[0]=new Image;/*"1DVG1.png";*/
patternImg[1]=new Image;/*"25BHP.png";*/
patternImg[2]=new Image;/*"2HA8A.png";*/
patternImg[3]=new Image;/*"2W6VI.png";*/
patternImg[4]=new Image;/*"3ABIA.png";*/
patternImg[5]=new Image;/*"3SY8C.png";*/
patternImg[6]=new Image;/*"4XNHV.png";*/
patternImg[7]=new Image;/*"4YE33.png";*/
patternImg[8]=new Image;/*"7BD8M.png";*/
patternImg[9]=new Image;/*"7JRTE.png";*/
patternImg[10]=new Image;/*"7LO10.png";*/
patternImg[11]=new Image;/*"84TJS.png";*/
patternImg[12]=new Image;/*"8FE34.png";*/
patternImg[13]=new Image;/*"8ONG7.png";*/
patternImg[14]=new Image;/*"9SD3N.png";*/
patternImg[15]=new Image;/*"D8ZGQ.png";*/
patternImg[16]=new Image;/*"DHBFG.png";*/
patternImg[17]=new Image;/*"EIAG9.png";*/
patternImg[18]=new Image;/*"FCS2K.png";*/
patternImg[19]=new Image;/*"FF5XJ.png";*/
patternImg[20]=new Image;/*"FKX6V.png";*/
patternImg[21]=new Image;/*"FV8TW.png";*/
patternImg[22]=new Image;/*"G7203.png";*/
patternImg[23]=new Image;/*"GE64E.png";*/
patternImg[24]=new Image;/*"GJ46D.png";*/
patternImg[25]=new Image;/*"IHGSO.png";*/
patternImg[26]=new Image;/*"IITEB.png";*/
patternImg[27]=new Image;/*"IZYK9.png";*/
patternImg[28]=new Image;/*"JVEF0.png";*/
patternImg[29]=new Image;/*"K0BJ8.png";*/
patternImg[30]=new Image;/*"KO769.png";*/
patternImg[31]=new Image;/*"KVUSJ.png";*/
patternImg[32]=new Image;/*"LOFR2.png";*/
patternImg[33]=new Image;/*"LSBK7.png";*/
patternImg[34]=new Image;/*"M6ZHX.png";*/
patternImg[35]=new Image;/*"M92BW.png";*/
patternImg[36]=new Image;/*"MJQD3.png";*/
patternImg[37]=new Image;/*"N1M2L.png";*/
patternImg[38]=new Image;/*"O5A0V.png";*/
patternImg[39]=new Image;/*"ONWD2.png";*/
patternImg[40]=new Image;/*"OVNJT.png";*/
patternImg[41]=new Image;/*"PDXCE.png";*/
patternImg[42]=new Image;/*"PSQPY.png";*/
patternImg[43]=new Image;/*"PYB7G.png";*/
patternImg[44]=new Image;/*"PZ9R6.png";*/
patternImg[45]=new Image;/*"QIJZ0.png";*/
patternImg[46]=new Image;/*"QM5K4.png";*/
patternImg[47]=new Image;/*"QT6B1.png";*/
patternImg[48]=new Image;/*"R6ORF.png";*/
patternImg[49]=new Image;/*"S0UN7.png";*/
patternImg[50]=new Image;/*"SCH87.png";*/
patternImg[51]=new Image;/*"SK6RR.png";*/
patternImg[52]=new Image;/*"TTH3H.png";*/
patternImg[53]=new Image;/*"UVHHS.png";*/
patternImg[54]=new Image;/*"UZHFJ.png";*/
patternImg[55]=new Image;/*"V1FBG.png";*/
patternImg[56]=new Image;/*"WSVEM.png";*/
patternImg[57]=new Image;/*"X080P.png";*/
patternImg[58]=new Image;/*"Y5CQ9.png";*/
patternImg[59]=new Image;/*"Y6Z01.png";*/
/*------------------------------------------------------*/
patternImg[0].name="patterns/1DVG1.png";
patternImg[1].name="patterns/25BHP.png";
patternImg[2].name="patterns/2HA8A.png";
patternImg[3].name="patterns/2W6VI.png";
patternImg[4].name="patterns/3ABIA.png";
patternImg[5].name="patterns/3SY8C.png";
patternImg[6].name="patterns/4XNHV.png";
patternImg[7].name="patterns/4YE33.png";
patternImg[8].name="patterns/7BD8M.png";
patternImg[9].name="patterns/7JRTE.png";
patternImg[10].name="patterns/7LO10.png";
patternImg[11].name="patterns/84TJS.png";
patternImg[12].name="patterns/8FE34.png";
patternImg[13].name="patterns/8ONG7.png";
patternImg[14].name="patterns/9SD3N.png";
patternImg[15].name="patterns/D8ZGQ.png";
patternImg[16].name="patterns/DHBFG.png";
patternImg[17].name="patterns/EIAG9.png";
patternImg[18].name="patterns/FCS2K.png";
patternImg[19].name="patterns/FF5XJ.png";
patternImg[20].name="patterns/FKX6V.png";
patternImg[21].name="patterns/FV8TW.png";
patternImg[22].name="patterns/G7203.png";
patternImg[23].name="patterns/GE64E.png";
patternImg[24].name="patterns/GJ46D.png";
patternImg[25].name="patterns/IHGSO.png";
patternImg[26].name="patterns/IITEB.png";
patternImg[27].name="patterns/IZYK9.png";
patternImg[28].name="patterns/JVEF0.png";
patternImg[29].name="patterns/K0BJ8.png";
patternImg[30].name="patterns/KO769.png";
patternImg[31].name="patterns/KVUSJ.png";
patternImg[32].name="patterns/LOFR2.png";
patternImg[33].name="patterns/LSBK7.png";
patternImg[34].name="patterns/M6ZHX.png";
patternImg[35].name="patterns/M92BW.png";
patternImg[36].name="patterns/MJQD3.png";
patternImg[37].name="patterns/N1M2L.png";
patternImg[38].name="patterns/O5A0V.png";
patternImg[39].name="patterns/ONWD2.png";
patternImg[40].name="patterns/OVNJT.png";
patternImg[41].name="patterns/PDXCE.png";
patternImg[42].name="patterns/PSQPY.png";
patternImg[43].name="patterns/PYB7G.png";
patternImg[44].name="patterns/PZ9R6.png";
patternImg[45].name="patterns/QIJZ0.png";
patternImg[46].name="patterns/QM5K4.png";
patternImg[47].name="patterns/QT6B1.png";
patternImg[48].name="patterns/R6ORF.png";
patternImg[49].name="patterns/S0UN7.png";
patternImg[50].name="patterns/SCH87.png";
patternImg[51].name="patterns/SK6RR.png";
patternImg[52].name="patterns/TTH3H.png";
patternImg[53].name="patterns/UVHHS.png";
patternImg[54].name="patterns/UZHFJ.png";
patternImg[55].name="patterns/V1FBG.png";
patternImg[56].name="patterns/WSVEM.png";
patternImg[57].name="patterns/X080P.png";
patternImg[58].name="patterns/Y5CQ9.png";
patternImg[59].name="patterns/Y6Z01.png";